service: sentiment-detection-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: 256
  timeout: 10
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - comprehend:DetectSentiment
          Resource:
            - '*'

functions:
  check-sentiment:
    handler: src/sentiment/index.handler
    environment:
      region: ${self:provider.region}
    events:
      - http:
          method: post
          path: sentiment

plugins:
  - serverless-plugin-typescript
